/*
Copyright (c) 2015, Patrick Weltevrede
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <string.h>
#include <stdlib.h>
#include "psrsalsa.h"

#define MaxNrJumps 100

int main(int argc, char **argv)
{
  int index, firstfiletoopen, curpanelnrx, curpanelnry, nokeypresses, showtotPol, nopaswing;
  int deviceID, nrpanelsx, nrpanelsy, nxsub;
  int titleset, dashed, datalinewidth, noylabel, overlayPA, overlayFine, nrJumps;
  int outline, outline_color;
  long i;
  float sigma_limit, titlech, boxch, labelch;
  float xsize, ysize, ysizepa, xtick, plotI1, plotI2;
  float plotl1, plotl2, plotp1, plotp2, PAoffset;
  float overlayalpha, overlaybeta, overlaypa0, overlayl0;
  float jump_longitude[MaxNrJumps], jump_offset[MaxNrJumps];
  char *filename_ptr, title[1000], PlotDevice[100];
  datafile_definition datain;
  psrsalsaApplication application;
  pgplot_options_definition pgplot_options;
  pgplot_clear_options(&pgplot_options);
  initApplication(&application, "ppolFig", "[options] inputfile(s)");
  application.switch_verbose = 1;
  application.switch_debug = 1;
  application.switch_header = 1;
  application.switch_headerlist = 1;
  application.switch_nocounters = 1;
  application.switch_filelist = 1;
  curpanelnrx = 0;
  curpanelnry = 0;
  nokeypresses = 0;
  showtotPol = 0;
  strcpy(PlotDevice, "?");
  nrpanelsx = 1;
  nrpanelsy = 1;
  xsize = 0.8;
  ysize = 1.0;
  ysizepa = 1.0;
  xtick = 0.0;
  nxsub = 0;
  sigma_limit = 3.0;
  titleset = 0;
  title[0] = 0;
  plotl1 = 0;
  plotl2 = 360;
  plotp1 = -180;
  plotp2 = 180;
  plotI1 = plotI2 = 0;
  PAoffset = 0;
  datalinewidth = 1;
  dashed = 0;
  noylabel = 0;
  overlayPA = 0;
  overlayFine = 1;
  outline = -1;
  nrJumps = 0;
  nopaswing = 0;
  titlech = 1;
  boxch = 1;
  labelch = 1;
  if(argc < 2) {
    printf("Program to plot output generated by ppol.\n\n");
    printApplicationHelp(&application);
    fprintf(stdout, "Other options affecting the output file:\n");
    fprintf(stdout, "-paoffset          Add this angle to PA (in degrees). Only affects plots.\n");
    fprintf(stdout, "-sigma             Set sigma limit on L required for PA calculation [def=%.1f].\n", sigma_limit);
    fprintf(stdout, "\nOther options affecting the plotting:\n");
    fprintf(stdout, "-1             Only plot PA-swing once (equivalent to -yrange \"0 180\").\n");
    fprintf(stdout, "-box_fmt       \"characterheight line_width font\" (default being \"%.1f %d %d\").\n", boxch, pgplot_options.box.box_lw, pgplot_options.box.box_f);
    fprintf(stdout, "-dash          Make L and V profiles dashed/dotted.\n");
    fprintf(stdout, "-device        Specify plotting device final plot.\n");
    fprintf(stdout, "-herrorbar     \"xleft xcentre xright y SizeOfMarkers lineWidth colourIndex\"\n");
    fprintf(stdout, "               Draw a horizontal errorbar. The position y is normalised\n");
    fprintf(stdout, "               between 0 and 1.\n");
    fprintf(stdout, "-herrorbar2    Identical to to -herrorbar option, but now for the PA panel,\n");
    fprintf(stdout, "               except that y is in degrees rather than being normalized.\n");
    fprintf(stdout, "-label_fmt       \"characterheight line_width font\" (default being \"%.1f %d %d\").\n", labelch, pgplot_options.box.label_lw, pgplot_options.box.label_f);
    fprintf(stdout, "-lw            Set linewidth used to plot data [def=%d].\n", datalinewidth);
    fprintf(stdout, "-N             \"nrx nry\" Create nrx by nry panels, rather than a single plot\n");
    fprintf(stdout, "               per page\n");
    fprintf(stdout, "-nokeypress    Do not wait for key presses to go to next page in output plot\n");
    fprintf(stdout, "               (by default this shouldn't happen if plotting to a file)\n");
    fprintf(stdout, "-noylabel      Disable labeling and numbers along y-axis.\n");
    fprintf(stdout, "-nopaswing     Do not produce the PA-swing panel.\n");
    fprintf(stdout, "-opm           Put OPM at this longitude and with this amount of degrees when\n");
    fprintf(stdout, "               using -paswing. You can use this option multiple times.\n");
    fprintf(stdout, "-outline       \"lw color\" Makes text of -text option appear in outline\n");
    fprintf(stdout, "-paswing       \"alpha beta pa0 l0\" Overlay PA-swing with these parameters.\n");
    fprintf(stdout, "-text          \"x y ch lw font color\" \"text\" plots text at this position in\n");
    fprintf(stdout, "               the top panel. See -textkeywords for possible keywords to use.\n");
    fprintf(stdout, "-textkeywords  Lists to keywords you can use in the -text and -title options.\n");
    fprintf(stdout, "-title \"...\"   Set title (default is file name). The title supports keywords\n");
    fprintf(stdout, "               listed by the -textkeywords option.\n");
    fprintf(stdout, "-title_fmt     \"characterheight line_width font\" (default being \"%.1f %d %d\").\n", titlech, pgplot_options.box.title_lw, pgplot_options.box.title_f);
    fprintf(stdout, "-totpol        Show the total amount of polarization.\n");
    fprintf(stdout, "-xrange        Specify longitude range covered in the plot in degrees.\n");
    fprintf(stdout, "-xrange_phase  Specify longitude range covered in the plot in phase.\n");
    fprintf(stdout, "-yrange        Specify PA-range covered in the plot.\n");
    fprintf(stdout, "-xsize         Set xsize of the plot [def=%.1f].\n", xsize);
    fprintf(stdout, "-ysize         Set ysize of the plot [def=%.1f].\n", ysize);
    fprintf(stdout, "-ysizepa       Set relative ysize of PA plot [def=%.1f].\n", ysizepa);
    fprintf(stdout, "-xticks        \"XTICK NXSUB\"  Adjust PGPLOT tickmarks [def=\"%.0f %d\"].\n", xtick, nxsub);

    printf("\n");
    printf("Please use the appropriate citation when using results of this software in your publications:\n\n");
    printf("More information about fitting position-angle swings and using the beam-width information can be found in:\n");
    printf(" - 	Rookyard et al. 2015, MNRAS, 446, 3367\n\n");
    printCitationInfo();
    terminateApplication(&application);
    return 0;
  }else if(argc >= 2) {
    for(i = 1; i < argc; i++) {
      index = i;
      if(processCommandLine(&application, argc, argv, &index)) {
 i = index;
      }else if(strcmp(argv[i], "-device") == 0) {
 strcpy(PlotDevice,argv[i+1]);
        i++;
      }else if(strcmp(argv[i], "-paoffset") == 0) {
 if(parse_command_string(application.verbose_state, argc, argv, i+1, 0, -1, "%f", &PAoffset, NULL) == 0) {
   printerror(application.verbose_state.debug, "ERROR ppolFig: Cannot parse '%s' option.", argv[i]);
   return 0;
 }
 i++;
      }else if(strcmp(argv[i], "-nokeypress") == 0) {
 nokeypresses = 1;
      }else if(strcmp(argv[i], "-totPol") == 0 || strcmp(argv[i], "-totpol") == 0) {
 showtotPol = 1;
      }else if(strcmp(argv[i], "-dash") == 0) {
 dashed = 1;
      }else if(strcmp(argv[i], "-noylabel") == 0) {
 noylabel = 1;
      }else if(strcmp(argv[i], "-N") == 0) {
 if(parse_command_string(application.verbose_state, argc, argv, i+1, 0, -1, "%d %d", &nrpanelsx, &nrpanelsy, NULL) == 0) {
   printerror(application.verbose_state.debug, "ERROR ppolFig: Cannot parse '%s' option.", argv[i]);
   return 0;
 }
        i++;
      }else if(strcmp(argv[i], "-xsize") == 0) {
 if(parse_command_string(application.verbose_state, argc, argv, i+1, 0, -1, "%f", &xsize, NULL) == 0) {
   printerror(application.verbose_state.debug, "ERROR ppolFig: Cannot parse '%s' option.", argv[i]);
   return 0;
 }
        i++;
      }else if(strcmp(argv[i], "-ysize") == 0) {
 if(parse_command_string(application.verbose_state, argc, argv, i+1, 0, -1, "%f", &ysize, NULL) == 0) {
   printerror(application.verbose_state.debug, "ERROR ppolFig: Cannot parse '%s' option.", argv[i]);
   return 0;
 }
        i++;
      }else if(strcmp(argv[i], "-sigma") == 0) {
 if(parse_command_string(application.verbose_state, argc, argv, i+1, 0, -1, "%f", &sigma_limit, NULL) == 0) {
   printerror(application.verbose_state.debug, "ERROR ppolFig: Cannot parse '%s' option.", argv[i]);
   return 0;
 }
        i++;
      }else if(strcmp(argv[i], "-ysizepa") == 0) {
 if(parse_command_string(application.verbose_state, argc, argv, i+1, 0, -1, "%f", &ysizepa, NULL) == 0) {
   printerror(application.verbose_state.debug, "ERROR ppolFig: Cannot parse '%s' option.", argv[i]);
   return 0;
 }
        i++;
      }else if(strcmp(argv[i], "-title") == 0) {
 strcpy(title, argv[i+1]);
 titleset = 1;
        i++;
      }else if(strcmp(argv[i], "-title_fmt") == 0) {
 if(parse_command_string(application.verbose_state, argc, argv, i+1, 0, -1, "%f %d %d", &titlech, &pgplot_options.box.title_lw, &pgplot_options.box.title_f, NULL) == 0) {
   printerror(application.verbose_state.debug, "ERROR ppolFig: Cannot parse '%s' option.", argv[i]);
   return 0;
 }
        i++;
      }else if(strcmp(argv[i], "-box_fmt") == 0) {
 if(parse_command_string(application.verbose_state, argc, argv, i+1, 0, -1, "%f %d %d", &boxch, &pgplot_options.box.box_lw, &pgplot_options.box.box_f, NULL) == 0) {
   printerror(application.verbose_state.debug, "ERROR ppolFig: Cannot parse '%s' option.", argv[i]);
   return 0;
 }
        i++;
      }else if(strcmp(argv[i], "-label_fmt") == 0) {
 if(parse_command_string(application.verbose_state, argc, argv, i+1, 0, -1, "%f %d %d", &labelch, &pgplot_options.box.label_lw, &pgplot_options.box.label_f, NULL) == 0) {
   printerror(application.verbose_state.debug, "ERROR ppolFig: Cannot parse '%s' option.", argv[i]);
   return 0;
 }
        i++;
      }else if(strcmp(argv[i], "-nopaswing") == 0) {
 nopaswing = 1;
      }else if(strcmp(argv[i], "-lw") == 0) {
 if(parse_command_string(application.verbose_state, argc, argv, i+1, 0, -1, "%d", &datalinewidth, NULL) == 0) {
   printerror(application.verbose_state.debug, "ERROR ppolFig: Cannot parse '%s' option.", argv[i]);
   return 0;
 }
        i++;
      }else if(strcmp(argv[i], "-xrange") == 0 || strcmp(argv[i], "-xrange_phase") == 0) {
 if(parse_command_string(application.verbose_state, argc, argv, i+1, 0, -1, "%f %f", &plotl1, &plotl2, NULL) == 0) {
   printerror(application.verbose_state.debug, "ERROR ppolFig: Cannot parse '%s' option.", argv[i]);
   return 0;
 }
 if(strcmp(argv[i], "-xrange_phase") == 0) {
   plotl1 *= 360.0;
   plotl2 *= 360.0;
 }
        i++;
      }else if(strcmp(argv[i], "-xticks") == 0) {
 if(parse_command_string(application.verbose_state, argc, argv, i+1, 0, -1, "%f %d", &xtick, &nxsub, NULL) == 0) {
   printerror(application.verbose_state.debug, "ERROR ppolFig: Cannot parse '%s' option.", argv[i]);
   return 0;
 }
        i++;
      }else if(strcmp(argv[i], "-yrange") == 0) {
 if(parse_command_string(application.verbose_state, argc, argv, i+1, 0, -1, "%f %f", &plotp1, &plotp2, NULL) == 0) {
   printerror(application.verbose_state.debug, "ERROR ppolFig: Cannot parse '%s' option.", argv[i]);
   return 0;
 }
        i++;
      }else if(strcmp(argv[i], "-yrange2") == 0) {
 if(parse_command_string(application.verbose_state, argc, argv, i+1, 0, -1, "%f %f", &plotI1, &plotI2, NULL) == 0) {
   printerror(application.verbose_state.debug, "ERROR ppolFig: Cannot parse '%s' option.", argv[i]);
   return 0;
 }
        i++;
      }else if(strcmp(argv[i], "-paswing") == 0) {
 if(parse_command_string(application.verbose_state, argc, argv, i+1, 0, -1, "%f %f %f %f", &overlayalpha, &overlaybeta, &overlaypa0, &overlayl0, NULL) == 0) {
   printerror(application.verbose_state.debug, "ERROR ppolFig: Cannot parse '%s' option.", argv[i]);
   return 0;
 }
 overlayPA = 1;
        i++;
      }else if(strcmp(argv[i], "-1") == 0) {
 plotp1 = 0.0;
 plotp2 = 180.0;
      }else if(strcmp(argv[i], "-text") == 0) {
 i += 2;
      }else if(strcmp(argv[i], "-herrorbar") == 0) {
 i += 1;
      }else if(strcmp(argv[i], "-herrorbar2") == 0) {
 i += 1;
      }else if(strcmp(argv[i], "-outline") == 0) {
 if(parse_command_string(application.verbose_state, argc, argv, i+1, 0, -1, "%d %d", &outline, &outline_color, NULL) == 0) {
   printerror(application.verbose_state.debug, "ERROR ppolFig: Cannot parse '%s' option.", argv[i]);
   return 0;
 }
 i++;
      }else if(strcmp(argv[i], "-opm") == 0) {
 if(parse_command_string(application.verbose_state, argc, argv, i+1, 0, -1, "%f %f", &jump_longitude[nrJumps], &jump_offset[nrJumps], NULL) == 0) {
   printerror(application.verbose_state.debug, "ERROR ppolFig: Cannot parse '%s' option.", argv[i]);
   return 0;
 }
 nrJumps++;
 if(nrJumps == MaxNrJumps) {
   fflush(stdout);
   printerror(application.verbose_state.debug, "ERROR ppolFig: Maximum number of %s options exceeded.", argv[i]);
   return 0;
 }
 i++;
      }else if(strcmp(argv[i], "-textkeywords") == 0) {
 str_list_replace_keys(0);
 terminateApplication(&application);
 return 0;
      }else {

 if(argv[i][0] == '-') {
   printerror(application.verbose_state.debug, "ppolFig: Unknown option: %s", argv[i]);
   printerror(application.verbose_state.debug, "\nRun ppolFig without command line arguments to show help");
   terminateApplication(&application);
   return 0;
 }else {
   if(applicationAddFilename(i, application.verbose_state) == 0)
     return 0;
 }
      }
    }
  }



  if(applicationFilenameList_checkConsecutive(argv, application.verbose_state) == 0) {
    return 0;
  }
  if(numberInApplicationFilenameList(&application, argv, application.verbose_state) == 0) {
    fflush(stdout);
    printerror(application.verbose_state.debug, "ERROR ppolFig: No files specified");
    return 0;
  }


  firstfiletoopen = 1;
  while((filename_ptr = getNextFilenameFromList(&application, argv, application.verbose_state)) != NULL) {

    if(firstfiletoopen == 0) {
      if(curpanelnrx == 0 && curpanelnry == 0) {
 if(nokeypresses == 0) {
   i = pgplot_device_type(PlotDevice, application.verbose_state);
   if(i < 3 || i > 10) {
     printf("Press a key in the terminal to continue\n");
     fflush(stdout);
     pgetch();
   }
 }
      }
    }


    if(!openPSRData(&datain, filename_ptr, application.iformat, 0, 1, 0, application.verbose_state))
      return 0;
    if(application.verbose_state.verbose) {
      fflush(stdout);
      printwarning(application.verbose_state.debug, "Input data contains %ld bins, %ld pulses, %ld polarizations and %ld frequencies.", (datain.NrBins), datain.NrSubints, (datain.NrPols), datain.NrFreqChan);
    }



    if(PSRDataHeader_parse_commandline(&datain, argc, argv, application.verbose_state) == 0)
      return 0;

    if(datain.poltype != POLTYPE_ILVPAdPA && datain.poltype != POLTYPE_PAdPA && datain.poltype != POLTYPE_ILVPAdPATEldEl) {
      fflush(stdout);
      printerror(application.verbose_state.debug, "ERROR ppolFig: File does not appear to contain PA data. ppolFig will not show data.");
      return 0;
    }
    if(datain.poltype == POLTYPE_PAdPA) {
      fflush(stdout);
      printerror(application.verbose_state.debug, "ERROR ppolFig: File does not appear to contain a pulse profile. ppolFig will not show data.");
      return 0;
    }
    if(datain.NrPols != 5 && datain.NrPols != 8) {
      fflush(stdout);
      printerror(application.verbose_state.debug, "ERROR ppolFig: When plotting previously calculated PA data, the number of polarization channels is expected to be 5 or 8, but it is %d", datain.NrPols);
      if(datain.NrPols == 2) {
 printerror(application.verbose_state.debug, "Note that the PPOLSHORT format can not be displayed with ppolFig.");
      }
      return 0;
    }
    float currentPanelScaling, currentPanelScalingx, currentPanelScalingy, viewport_left, viewport_right, viewport_top, viewport_bottom;
    currentPanelScaling = 1;
    viewport_left = 0.1;
    if(nrpanelsx > 1) {
      currentPanelScalingx = xsize/((nrpanelsx-1)*0.2 + nrpanelsx*xsize);
      currentPanelScaling = currentPanelScalingx;
      viewport_left += curpanelnrx*currentPanelScalingx*0.1;
      viewport_left += curpanelnrx*currentPanelScalingx*xsize;
      viewport_left += curpanelnrx*currentPanelScalingx*0.1;
    }
    viewport_right = viewport_left+xsize;
    if(nrpanelsx > 1) {
      viewport_right = viewport_left;
      viewport_right += currentPanelScalingx*xsize;
    }
    viewport_bottom = 0.35-0.25*ysize*ysizepa;
    if(nrpanelsy > 1) {
      currentPanelScalingy = (0.55*ysize + 0.25*ysize*ysizepa)/((nrpanelsy-1)*(0.35-0.25*ysize*ysizepa) + nrpanelsy*(0.55*ysize + 0.25*ysize*ysizepa) + (nrpanelsy-1)*(1-0.35-0.55*ysize));
      if(currentPanelScalingy < currentPanelScaling)
 currentPanelScaling = currentPanelScalingy;
      viewport_bottom += (nrpanelsy-curpanelnry-1)*currentPanelScalingy*(0.35-0.25*ysize*ysizepa);
      viewport_bottom += (nrpanelsy-curpanelnry-1)*currentPanelScalingy*(0.55*ysize + 0.25*ysize*ysizepa);
      viewport_bottom += (nrpanelsy-curpanelnry-1)*currentPanelScalingy*(1-0.35-0.55*ysize);
    }
    viewport_top = viewport_bottom + (0.55*ysize + 0.25*ysize*ysizepa);
    if(nrpanelsy > 1) {
      viewport_top = viewport_bottom;
      viewport_top += currentPanelScalingy*(0.55*ysize + 0.25*ysize*ysizepa);
    }
    if(curpanelnrx == 0 && curpanelnry == 0)
      ppgpage();
    curpanelnrx++;
    if(curpanelnrx == nrpanelsx) {
      curpanelnrx = 0;
      curpanelnry++;
    }
    if(curpanelnry == nrpanelsy)
      curpanelnry = 0;
    if(datain.NrSubints > 1 || datain.NrFreqChan > 1) {
      fflush(stdout);
      printwarning(application.verbose_state.debug, "WARNING ppolFig: Only showing polarization of the first subint/frequency channel");
    }
    pgplot_options.viewport.dxplot = viewport_left - 0.1;
    pgplot_options.viewport.xsize = (viewport_right - 0.1 - pgplot_options.viewport.dxplot)/0.8;
    pgplot_options.viewport.ysize = (viewport_top - viewport_bottom)/(0.55 + 0.25*ysizepa);
    pgplot_options.viewport.dyplot = viewport_top - 0.35 - 0.55*(viewport_top - viewport_bottom)/(0.55 + 0.25*ysizepa);
    strcpy(pgplot_options.viewport.plotDevice, PlotDevice);
    pgplot_options.viewport.noclear = 1;
    pgplot_options.viewport.dontclose = 1;
    pgplot_options.viewport.dontopen = !firstfiletoopen;
    pgplot_options.box.box_xtick = xtick;
    pgplot_options.box.box_nxsub = nxsub;
    if(titleset)
      strcpy(pgplot_options.box.title, title);
    else
      strcpy(pgplot_options.box.title, datain.filename);
    pgplot_options.box.title_ch = titlech*currentPanelScaling;
    pgplot_options.box.label_ch = labelch*currentPanelScaling;
    pgplot_options.box.box_labelsize = boxch*currentPanelScaling;
    int showEll2 = 0;
    datafile_definition *padist_ptr, *elldist_ptr;
    padist_ptr = NULL;
    elldist_ptr = NULL;
    pgplotPAplot(datain, showtotPol, nopaswing, showEll2, &pgplot_options, "Pulse longitude [deg]", "I,Linear,V", "PA [deg]", "\\gx [deg]", plotl1, plotl2, plotI1, plotI2, plotp1, plotp2, PAoffset, sigma_limit, datalinewidth, ysizepa, dashed, noylabel, "-text", "-herrorbar", "-herrorbar2", "-verrorbar", "-verrorbar2", argc, argv, outline, outline, outline_color, overlayPA, overlayalpha, overlaybeta, overlaypa0, overlayl0, overlayFine, nrJumps, jump_longitude, jump_offset, padist_ptr, elldist_ptr, application.verbose_state);
    if(firstfiletoopen) {
      ppgqid(&deviceID);
    }
    closePSRData(&datain, 0, application.verbose_state);
    firstfiletoopen = 0;
  }
  ppgend();
  terminateApplication(&application);
  return 0;
}
